
[secrets]
stream_key = "abc"         # youtube stream key
api_key = ""            # google api key

[stream]
title = "my test stream"            # name of the stream
privacyStatus = "private"           # privacy on youtube, private/public
